### ISSUE TITLE
Ambiguity between solute and solvent

### ISSUE THREAD

**Issue by beelerchris** [chemgymrl/chemgymrl#114]
Solute and solvent seemed to be used interchangeably throughout the code. All solvents are being stored in the solute dictionaries.

**Comment by rateldajer** [comment]
is this still a problem?

**Comment by beelerchris** [comment]
The ambiguity stems from the definition of the solute_dict. Each key in solute_dict is a solute material and the values of each key are the various solvents that solute is dissolved in. No issue.

**Comment by beelerchris** [comment]
Solvent variables in specific extractions were labelled as solutes. Fixed with latest PR.
