### ISSUE TITLE
No purity term in extraction reward function

### ISSUE THREAD

**Issue by beelerchris** [chemgymrl/chemgymrl#116]
There is not a term in the Extraction Bench reward function that takes the purity of the desired material into account.

https://github.com/chemgymrl/chemgymrl/blob/b664b930c5c09ed5dcd0dea269786d20c030fb17/chemistrylab/chem_algorithms/reward.py#L311

**Comment by rateldajer** [comment]
is this issue completed now?

**Comment by beelerchris** [comment]
This issue is now solved with the recent pull request merge. The issue of having a weighted purity reward can be a separate issue.
