### ISSUE TITLE
Different Action Spaces

### ISSUE THREAD

**Issue by mbaula** [chemgymrl/chemgymrl#12]
For testing out which action spaces work better there needs to be different variants.

1. Continuous actions [Add X of species 0, ..., Add Y of species n, Change temperature, Change volume]
1. Discrete actions (classification) [Add reagent 0, add reagent 1, Add reagent 0 and 1, ..., Add reagents 0 through n, increase/decrease temperature, increase/decrease pressure, take time step] (state array needs button presses since the last time step)
3. Discrete actions (regression) [Add reagent 0, ..., Add reagent n, change temperature, change volume, take time step] (state array needs button presses since last time step)

**Comment by NicholasPaquin** [comment]
This is a slightly vague issue, needs elaboration on how the action spaces are to be changed

**Comment by rateldajer** [comment]
How does this work presently? Isn't there a continuous value attached to each bench action as well?

**Comment by Sriram94** [comment]
I do not think this is an issue. Some benches have discrete actions and others have continuous actions based on need. I am closing this now, though it can be opened again if anyone thinks we should change something.
