### ISSUE TITLE
Problem with website access when typing url directly.

### ISSUE THREAD

**Issue by rateldajer** [chemgymrl/chemgymrl#120]
When going directly to chemgymrl.com or some other variants of that there are security certificate issues that block the browser. 

Observed situations:
- OS: Mac OS 10.15, browser: chrome, url: http(s)://chemgymrl.com
   - cannot reach page
- OS: Mac OS 10.15, browser: chrome, url: https://www.chemgymrl.com
   - connection is not private warning

**Comment by beelerchris** [comment]
This seems to be fixed now. Am I correct @rateldajer?
