### ISSUE TITLE
Add observation state to all benches

### ISSUE THREAD

**Issue by mbaula** [chemgymrl/chemgymrl#15]
Each bench needs to have it's own true underlying state as well as the observation state which represents the believed state of the contents of a vessel by the lab manager. Once each bench can have access to this then the communication between the lab manager and the bench agent can be complete consisting of:
- vessels with a belief about their contents
- desired output

_First task_: complete the state of the system with regard to this feature, then create issues for each and assign to appropriate team member

Status and plan:
- **Which benches already have this enabled?**
   - Reaction bench?
- **Which benches do not have this enabled?**
   - Extraction bench

**Comment by rateldajer** [comment]
was this resolved already? it sounds like it must exist already for the lab manager to work at all.

**Comment by Sriram94** [comment]
I think this has already been fixed for the extraction bench (other benches already had this defined). I am assigning Chris to this, who can close this if he can confirm that it is already done.
