### ISSUE TITLE
Extractions without a reaction file identifier give an IO error during initialization

### ISSUE THREAD

**Issue by ksprague1** [chemgymrl/chemgymrl#157]
To reproduce: 

env = gym.make('Oil_Water_Extract-v1')

alternative:

env = gym.make('MethylRed_Extract-v2')

Trace:

File ~\anaconda3\envs\chemgym\lib\site-packages\chemistrylab\reactions\reaction_base.py:217, in File ~\anaconda3\envs\chemgym\lib\site-packages\chemistrylab\extract_bench\extract_bench_v1.py:303, in ExtractWorld_Oil_v1.__init__(self)
    302 def __init__(self):
--> 303     super(ExtractWorld_Oil_v1, self).__init__(
    304         extraction='water_oil',
    305         extraction_vessel=oil_vessel(),
    306         target_material='Na'
    307     )

File ~\anaconda3\envs\chemgym\lib\site-packages\chemistrylab\extract_bench\extract_bench_v1_engine.py:138, in ExtractBenchEnv.__init__(self, n_steps, dt, extraction, n_vessel_pixels, max_valve_speed, extraction_vessel, reaction, reaction_file_identifier, in_vessel_path, solvents, target_material, out_vessel_path, extractor)
    122 # validate the input parameters provided to the extract bench engine
    123 self.input_parameters = self._validate_parameters(
    124     n_steps=n_steps,
    125     dt=dt,
   (...)
    135     out_vessel_path=out_vessel_path
    136 )
--> 138 self.reaction = self.input_parameters["reaction"](
    139     reaction_file_identifier=self.input_parameters["reaction_file_identifier"],
    140     target_material=target_material,
    141 )
    143 # set the validated input parameters
    144 self.n_steps = copy.deepcopy(self.input_parameters["n_steps"])

File ~\anaconda3\envs\chemgym\lib\site-packages\chemistrylab\reactions\reaction_base.py:79, in _Reaction.__init__(self, reaction_file_identifier, target_material, avoid_material, dt, overlap, solver)
     76 self.name = "base_reaction"
     78 # ensure the requested reaction file is found and accessible
---> 79 reaction_filepath = self._find_reaction_file(reaction_file=reaction_file_identifier)
     81 # acquire the necessary parameters from the reaction file
     82 reaction_params = self._get_reaction_params(reaction_filepath=reaction_filepath)

File ~\anaconda3\envs\chemgym\lib\site-packages\chemistrylab\reactions\reaction_base.py:217, in _Reaction._find_reaction_file(reaction_file)
    212     output_reaction_file = os.path.join(
    213         r_files_dir,
    214         reaction_file + ".py"  # re-add the extension
    215     )
    216 else:
--> 217     raise IOError("ERROR: Requested Reaction File Not Found in Directory!")
    219 return output_reaction_file

OSError: ERROR: Requested Reaction File Not Found in Directory!

**Comment by beelerchris** [comment]
Reaction files in extraction bench are just used for a list of possible target materials. This should be replaces with just a list of possible products.

**Comment by ksprague1** [comment]
Did some digging and made it such that the extractions work (for the most part)

# How to fix in general:

1. create instances of your materials (Ex H -> H())
    - This needs to happen when preparing the initial vessel and in reset
2. Add 'targets' input parameter to reset() and get_observation_space()
    - This step may be more involved to make the obervation space match the observations
3. Add in reaction file with the prodects and solvents of the reaction


Note: I did this in my branch but it is on an older version of the code so I may make a new branch and do a pull request there.

**Comment by beelerchris** [comment]
All available extractions now have reaction files. New extractions will have reaction files created if needed from now on.
