### ISSUE TITLE
Material dictionary overflow values in Reaction Bench

### ISSUE THREAD

**Issue by beelerchris** [chemgymrl/chemgymrl#162]
When training an RL agent on a reaction bench environment (specifically only "GenWurtzReact-v1" confirmed so far), the environment eventually returns computationally infinite rewards.

**Comment by beelerchris** [comment]
The increase in reward doesn't happen for several hundred (or thousand) episodes into training.

**Comment by beelerchris** [comment]
This occurs because the amount of materials in the reaction vessel become extremely large, going from orders of less than 1e-6 to over 1e+20 in a single environment step.

**Comment by beelerchris** [comment]
**Example**
Step: 19 
Material Dictionary: {..., '3-chlorohexane': [<chemistrylab.chem_algorithms.material.ThreeChlorohexane object at 0x7f401c1b6630>, 6.595073113441434e-05, 'mol'], ..., 'dodecane': [<chemistrylab.chem_algorithms.material.Dodecane object at 0x7f401c1b62e8>, 0.057315945896099306, 'mol'], ...}

Step: 20
Material Dictionary: {..., '3-chlorohexane': [<chemistrylab.chem_algorithms.material.ThreeChlorohexane object at 0x7f40147e1780>, 3664898.348138574, 'mol'], ..., 'dodecane': [<chemistrylab.chem_algorithms.material.Dodecane object at 0x7f401c1679e8>, 2.478817822070162e+20, 'mol'], ...}

The material dictionary at Step 19 is typical for this bench but not at step 20. The action sequence for this episode is not abnormal and manually inputting this action sequence in the environment does not reproduce this behavior. Once this occurs, it doesn't necessarily happen every subsequent episode.

**Comment by beelerchris** [comment]
The issue occurs while scipy.integrate.solve_ivp solves the reaction differential equation. The problem occurs for various atol/rtol values and all solver methods.

**Comment by beelerchris** [comment]
As the concentrations of the reactants goes to zero, the rates should do the same, however the concentration of the reactants becomes negative as the DE is evolved in time (|A| goes from 1e-15 to -1e-15), which creates a positive feedback loop of speeding up the rates. The negative concentrations eventually get clipped to 0 but this doesn't undo the change to the products concentrations.

**Comment by Sriram94** [comment]
Fixed by 62c92de1ed19ef11c3dba12b7459f774db46245f.
