### ISSUE TITLE
Solute staying solute after solvent is boiled off

### ISSUE THREAD

**Issue by beelerchris** [chemgymrl/chemgymrl#163]
When a solvent is boiled off in distillation bench, any solutes remaining in the distillation beaker stay as solutes dissolved in nothing. They should become their own materials with layer positions so they are visualized in the observations.

**Comment by beelerchris** [comment]
We will need to add a precipitation function (reverse of dissolve function) to material class.

**Comment by Sriram94** [comment]
Fixed by 62c92de1ed19ef11c3dba12b7459f774db46245f.
