### ISSUE TITLE
Unit test errors

### ISSUE THREAD

**Issue by cbellinger27** [chemgymrl/chemgymrl#167]
The last step in the installation instruction (https://chemgymrl.readthedocs.io/en/latest/Installation/) is to run the unit tests with the following code: python3.8 -m unittest discover -p "*test*.py".  The last fifty or so unit tests fail. The output is copied into the attached file. Note, running RL experiments on the installed gym works fine. The issue seems be specifically with the unit test code. 
[unit_test_errors.txt](https://github.com/chemgymrl/chemgymrl/files/10500729/unit_test_errors.txt)

**Comment by beelerchris** [comment]
We should make the tests less specific to single environment for a bench to avoid future issues when adding or removing benches.

**Comment by beelerchris** [comment]
For example, we devise a set of unit tests for Reaction Bench and then run them over all registered reaction bench environments, instead of having a separate overlapping set of tests for each reaction bench environment.

**Comment by ksprague1** [comment]
A lot of these errors are from extraction bench. I also ran into the same issues when doing QA testing on extraction bench:

------------------------------------------------------------
GenWurtzExtract-v1:Failed:
'NoneType' object has no attribute 'dissolve'

------------------------------------------------------------
WurtzExtract-v1:Failed:
'NoneType' object has no attribute 'dissolve'

------------------------------------------------------------
WurtzExtractCtd-v1:Passed
------------------------------------------------------------
WaterOilExtract-v1:Failed:
'NoneType' object has no attribute 'dissolve'


Some Traceback:

File "../../..\chemistrylab\extract_bench\extract_bench_v1_engine.py", line 528, in step
    purity_threshold=self.min_purity_threshold
  File "../../..\chemistrylab\chem_algorithms\reward.py", line 455, in validate_vessels
    print_flag = False
  File "../../..\chemistrylab\chem_algorithms\reward.py", line 325, in calc_vessel_purity
    dis_mats = desired_material_class.dissolve()
AttributeError: 'NoneType' object has no attribute 'dissolve'

**Comment by ksprague1** [comment]
Traces to calc_vessel_purity() which no longer works with extractions

**Comment by beelerchris** [comment]
I've fixed the unit tests in my latest PR #170
