### ISSUE TITLE
Is Docs/QuickStart out of date?

### ISSUE THREAD

**Issue by rateldajer** [chemgymrl/chemgymrl#200]
It looks like the Quickstart.md file is completely out of date now, is that right @ksprague1? There are conflicts between these install/start instructions and the ones at
- https://chemgymrl.readthedocs.io/en/latest/Installation.html (this seems like the latest, right?)
- and chemgymrl/README.md

**Comment by ksprague1** [comment]
I'll run through the website and make sure each page is up to date (and if they don't make sense to include amymore potentially remove them)

**Comment by beelerchris** [comment]
Looks like the website is up to date now
