### ISSUE TITLE
Add WhatIsChemGymRL content to index.rst

### ISSUE THREAD

**Issue by rateldajer** [chemgymrl/chemgymrl#204]
The landing page for the readthedocs should be the descriptive page:
https://github.com/chemgymrl/chemgymrl/blob/main/docs/WhatIsChemGymRL.md

I think the easiest way to do this is to move all the text in that page into index.rst and refactor any links to WhatIsChemGymRL.md (if any) back to index.

**Comment by ksprague1** [comment]
Pointing chemgymrl.com to the docs site isn't functional right now
![image](https://github.com/chemgymrl/chemgymrl/assets/23179021/e1c844bd-f168-42ad-a128-f3d76512cbe6)

**Comment by ksprague1** [comment]
I added in some of the WhatIsChemGymRL content to the index as well as added an about us section in the new web-update branch:

https://docs.chemgymrl.com/en/web-update/index.html

https://docs.chemgymrl.com/en/web-update/About.html

Let me know if it would be better to just have all of the WhatIsChemGymRL information in the main page and just remove the WhatIsChemGymRL page.
