### ISSUE TITLE
Implement Viewable Consecutive States

### ISSUE THREAD

**Issue by mbaula** [chemgymrl/chemgymrl#3]
- Implement functionality such that consecutive states are viewable when the agent/user sees the result of a completed action.
- Determine how many 'frames' of action are used and make this adjustable.
- As a default, we will allow the agent/user to see all the states between the most recent action and the current time-step
- Model this functionality similar to how the Atari operates.

**Comment by rateldajer** [comment]
It's not clear this is fundamentally required. A Markovian agent doesn't need this because it can choose to remember whatever elements it sees if that is part of it's approach.
