### ISSUE TITLE
Drain Function Error

### ISSUE THREAD

**Issue by mitchellshahen** [chemgymrl/chemgymrl#85]
Pouring by volume in extraction bench from any vessel to the extraction vessel requires a second instance of running the `fully_mix` function to properly update. Any other pour by volume event updates the layers with a single instance of running `fully_mix`.

However, in running `fully_mix` for any other pouring by volume between ancillary vessels or pouring the extraction vessel into an ancillary vessel, we encounter an error in the vessel class's use of `separate.map_to_state`.

The current state of the code has `fully_mix` running twice in all extractions, but only for the pouring of an ancillary vessel into the extraction vessel.

**Comment by beelerchris** [comment]
There seems to be a bug in the `fully_mix` event. Replacing the `fully_mix` event with calling the `mix` function with a largely negative mixing parameter seems to be the appropriate fix.
