### ISSUE TITLE
Plots are being Clipped

### ISSUE THREAD

**Issue by mitchellshahen** [chemgymrl/chemgymrl#89]
Plots shouldn't have to be clipped because a spectral signature of 1 indicates that 100% of the light is being absorbed.

**Comment by beelerchris** [comment]
This seems to be an issue with using the hand-crafted spectra. The appropriate change is to obtain the proper spectra for each material and having the height of the spectra relative to the purity of the material in the vessel. UV-Vis may not be enough. We will likely need IR as well.
